language: bash
os: linux
sudo: required
services:
- docker
jobs:
  include:
  - stage: release
    if: branch = semantic-release-2
    language: node_js
    node_js: '8'
    provider: script
    skip_cleanup: true
    before_script:
    - "./.travis/release.bash"
    script:
    - nvm install lts/*
    - npx semantic-release
  - stage: deploy
    on:
      tags: true
    provider: script
    script:
    - "./.travis/docker_push.bash"
    skip_cleanup: true
env:
  global:
  - secure: OL75lxUJwRqwvI4CcJpYEzZu5sGIV86YS/XH1/uwR/tee87GPUt17KK7HHMjdPufrBayfSCQC4f/LTf9vJbjG1PcvQs9rsFFpO1gD6YwUB92qodLFLum8MGnkGGwgEC7PM8sqT+a9+vUt2RcZCGiTl05cv4bV9t9KKHASLBKKZXPBJzwELcZXcRcTT5dIsvh02F77vp8udoruXO7q3bFCBdPwygIXSIBElDm4y1gm37dGChuiUEjhDv/ZFKs0Xz4js0wipZvvaI6OXmJZ/5RMqXctRMtx6az9o0h7lsAu4eQzwE1TfZebNREc2/0FeRbJT4PVQ+ZEBLK+ExkGbb3rd+xutv1jcfB5v5T/6M3KH5H2sCf0ZzJjyys1pOG6uLDh0gGdcm+QSiwaj5bRVF2Vaim8pqetDU+Afzp7jcNBooSXOe488u/hgUQhe+d5Fc9SqWGHuauu8WUdrD2XbxDz/NALUaT3butUuwadgHd9+7wpMLQtouzv8fxwAr3qiz2+yBvWntLKhrF/tER9NSP+PAQYm0S6ncvZ8CzGSpk11VsSzWpSGM3YgkXiyCmC0lttRX8zFWYFQpQt2eSp0sN0eP7pMqPxM2zx/qNBgUkZrM3pLOFCfopdFlErb7ggqZTE3bLwBo4RDtQ0eZSAFOnto5TTrLfELKlMzczE+vYw1U=
  - secure: NbedbNLp2TrFJ01/APYBCIMQVTNKiyRJvFEu0VxRrr7shRcuRdn+lX7cgAaqimYppicHmyhnIff6X0RBveKATd0t/NEEzfwx2L8/gAYJkGF4eHI4wUBYgiZDqOZWFigG8vUR48vuJZSqGUfIjBcIZHth76nVm1vEXV/vZVoEdTxRFKdwbNzXcyJlw2VzX/FcI7l/9frgvmlsvlxwn8vjO5rCC2bM+2FILeLcmk+67BmXt003lFYfdTXbzy3QlRb123pLPhXRjb+ywpI9qpaKLHcoPVhU7c02G9py2Fyp3VlE8VDyh5T9BCcvuOE8FIwDQHxj5NWzdDNVi1XsMweTRTSwWL7onogG5I1YoQ6g/zYOk+6nxTPFaml1wwdWT6eQ5c/vG4wPN3GE4qRGgG72vHmyKQUuihrTeHwOjUL9C8Skv0S1F8fcYQZp2AaMKEKESaaGfJO8a6rZ+z8oNrX06tKjaxQKLAS7rauluZQirxCU5HeZ/hD67qQqqs/jO32FeuOQFW3dEwrqtw77AXjVqMkmQrYFMVKFRrZYjt15z7pqY4KdQrpq6rEwqKvygBUvo/CCAsABOuMJgdTeaZ1NuUSl21Ddb9+jDOuIe+loS5ayl9bvq8wNdZsWRmk253pq6WhKXXlBcF1K+HCIpuLEEf8nUCr7d5Ry8Viiw1Nm35g=
  - secure: KCIeDXYXgjGEx4t2WZeRkucbc89GE/MkuV78+V43N30C3tiYJSN8GZK5XEihTUxQEyq5X26HzsEmIynZYDST611+CQ/A3x6NJICioAz6Kqw0rpoTHOYX1wRq00jQt1BPhzlt8IUcpY1fx3htoF8frGeb5q/xyN+f1m5zPr6RGo4VE3bofMB0zEcv1mLq7Q7gl/HuZIJg0pZFXtH5QLs2klCv5q65IxoUAYA/QdHh7CdIniTcRMCDx7acrMjW2ZG1btb/7Eu5HLBSVQQICUh8KOv1y+3lV+0VPvyb64W3ygMz//1napGSe3NMpRoCF00fixOSTF1/eSJEj6A/CNR0azwHjEynEUFdiGrUi9/CaGWsJ2MKkEhb5NWUeSqjGi9qD7Zo9JSk5eFdqP5iRrsJE9tiNJfiTMuQ7lXFTXjFs+pl9KOwy0UP6PbMnxgsZm2jXixtee4EDhL/cdsOSq7CHP7bvndVoMn4JosJlWyZ1ggD5NnIQzZYf30yBJ3rAkvHw+HSsZUqabYcz2Qf6jhox3EGfs0QNG1EjMjP2KZiCVi9AGPRwUzeOYwkk7mxaZSSTp/agaIb0k++vO/QCUBtJOXBjaA85asY5FPqzsw+zzqo18/tWYSfo7AYXnJvXza7pMQml68hU+Pn9wF6my6MfXOWuuhM2XIRxw4fOTlmQrk=
